---
language: ruby

rvm:
  - 2.6.6

before_install:
  - gem update --system
  - gem install bundler --no-document

branches:
  only:
    - master
    - /^travis.*/

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script: bundle exec rake

    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: rubygems
          api_key: $RUBYGEMS_KEY
          gem: animatedledstrip-client
          on:
            all_branches: true
