---
language: ruby

rvm:
  - 2.6.6

branches:
  only:
    - master
    - /^travis.*/
    - /^v.*/

stages:
  - name: test
  - name: deploy
    if: branch =~ ^v.*$

jobs:
  include:
    - stage: test
      before_install:
        - gem update --system
        - gem install bundler --no-document
      script: bundle exec rake

    - stage: deploy
      before_install:
        - gem update --system
        - gem install bundler --no-document
      install: skip
      script: skip
      deploy:
        - provider: rubygems
          api_key: $RUBYGEMS_KEY
          gem: animatedledstrip-client
          on:
            all_branches: true
